export const EnvConfiguration = () => ({
    environment: process.env.NODE_ENV || 'development',
    loggerLevel: process.env.LOGGER_LEVEL || 'development',
    port: process.env.PORT || 3000,
    dbPassword: process.env.DB_PASSWORD,
    dbName: process.env.DB_NAME,
    dbHost: process.env.DB_HOST,
    dbPort: process.env.DB_PORT,
    dbUser: process.env.DB_USER,
    jwtSecret: process.env.JWT_SECRET,
    googleClientId: process.env.GOOGLE_CLIENT_ID,
    googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
    googleCallbackUrl: process.env.GOOGLE_CALLBACK_URL,
    mailerSecret: process.env.MAILER_SECRET,
    mailerEmail: process.env.MAILER_EMAIL,
    mailerService: process.env.MAILER_SERVICE,
    sentryDsn: process.env.SENTRY_DSN,
    sentryEnabled: process.env.SENTRY_ENABLED,
});