name: '🙊 Typos'

on:
  push:

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛬
        uses: actions/checkout@v6
      - name: 🙊 Run code spell checker to check typos
        uses: crate-ci/typos@v1.42.2
